name: Every Day (GSheets, Passport)

on:
  schedule:
    # Runs at 3:00 UTC every day
    - cron:  '0 3 * * *'
  workflow_dispatch:


jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_Port }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      INDEXER_DB_HOST: ${{ secrets.INDEXER_DB_HOST }}
      INDEXER_DB_PORT: ${{ secrets.INDEXER_DB_PORT }}
      INDEXER_DB_NAME: ${{ secrets.INDEXER_DB_NAME }}
      INDEXER_DB_USER: ${{ secrets.INDEXER_DB_USER }}
      INDEXER_DB_PASSWORD: ${{ secrets.INDEXER_DB_PASSWORD }}
      MACI_DB_HOST: ${{ secrets.MACI_DB_HOST }}
      MACI_DB_PORT: ${{ secrets.MACI_DB_PORT }}
      MACI_DB_NAME: ${{ secrets.MACI_DB_NAME }}
      MACI_DB_USER: ${{ secrets.MACI_DB_USER }}
      MACI_DB_PASSWORD: ${{ secrets.MACI_DB_PASSWORD }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Upload non-GS Allo data From Sheet
      run: python automations/upload_non_gs_allo_data.py
    - name: Upload Passport Model Scores
      run: python automations/upload_passport_model_scores.py
      timeout-minutes: 55


